apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop
patchesStrategicMerge:
- service.yaml
resources:
- namespace.yaml
- upstream/release/kubernetes-manifests.yaml
- ingress.yaml
