apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-z1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/47309ca5-07cb-421a-9190-601d13a30cdf/resourceGroups/aksdemoaks-rg/providers/Microsoft.Compute/disks/aks-disk-z1
    volumeAttributes:
      cachingMode: ReadOnly
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-z2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/47309ca5-07cb-421a-9190-601d13a30cdf/resourceGroups/aksdemoaks-rg/providers/Microsoft.Compute/disks/aks-disk-z2
    volumeAttributes:
      cachingMode: ReadOnly
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-z3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/47309ca5-07cb-421a-9190-601d13a30cdf/resourceGroups/aksdemoaks-rg/providers/Microsoft.Compute/disks/aks-disk-z3
    volumeAttributes:
      cachingMode: ReadOnly
      fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk-z1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-azuredisk-z1
  storageClassName: ""
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk-z2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-azuredisk-z2
  storageClassName: ""
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk-z3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-azuredisk-z3
  storageClassName: ""