apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-external-ingress
  namespace: shop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: shop.lemarchand.io
    http:
      paths:
      - backend:
          serviceName: frontend-external
          servicePort: 80