apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-external-ingress
  namespace: shop
spec:
  rules:
  - host: shop.localhost
    http:
      paths:
      - backend:
          serviceName: frontend-external
          servicePort: 80