apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop
patchesStrategicMerge:
- service.yaml
- redis.yaml
- loadgenerator.yaml
resources:
- namespace.yaml
- storage.yaml
- upstream/release/kubernetes-manifests.yaml