apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  template:
    spec:
      containers:
      - name: main
        image: kubernetes/pause
      initContainers:
      - $patch: delete
        name: wait-frontend